added animations
bckrm/silverado pull request #70
Opened 2021-01-28 21:43 UTC by kcbreuil

2021-01-31 12:34 UTC, kcbreuil commented
@asasmith been trying to debug this. Looks like the animations (two of the 4) render a div container to sit in them. I am not quite sure how to target this plain div. Do you have any insight on this? I have a feeling it's how Leslie exported them.

2021-02-02 01:26 UTC, asasmith commented on src/components/heroAnimation.js
> +        window.addEventListener('resize', handleResize);
You should be able to move this into the `useEffect` below. Make sure to remove the event listener in the return function

2021-02-02 01:30 UTC, asasmith commented on src/components/initiativesAnimation.js
> +            <span className="icons">
these should probably just be `div`'s

2021-02-02 01:34 UTC, asasmith commented on src/components/indexHero.js
> +
remove commented code

2021-02-02 01:35 UTC, asasmith commented on src/components/fullWidthImageWithText.js
> +    // } = image;
remove commented code

2021-02-02 01:35 UTC, asasmith commented on src/components/fullWidthImageWithText.js
> +// import Img from 'gatsby-image';
remove commented code

2021-02-02 01:35 UTC, asasmith commented on src/components/fullWidthImageWithText.js
> +            {/* <Img fluid={fluid} /> */}
remove commented code

2021-02-02 01:36 UTC, asasmith commented on src/components/fullWidthImageWithText.js
> +    // image: PropTypes.object.isRequired,
remove commented code

2021-02-03 01:17 UTC, asasmith requested changes

2021-02-03 01:17 UTC, asasmith commented on src/components/initiativesAnimation.js
> +    ${tw`grid grid-cols-5 grid-rows-5 justify-center`}
5 rows doesn't work on larger screens, there's too much space between the wrapper element and the next section. If you need that many rows for smaller screens use whichever use one of the media query prefixes

2021-02-03 01:17 UTC, asasmith commented on src/components/initiativesAnimation.js
> +    }
I'm not a fan of this naming convention. I wouldn't truncate names like `incu`. I'd also add something that makes it very clear if that styling is focused on an animation or text element `-animation` or `-text`.

2021-02-03 01:17 UTC, asasmith commented on src/components/initiativesAnimation.js
> +    };
same comment about class/id naming convention

2021-02-03 01:17 UTC, asasmith commented on src/components/initiativesText.js
> +export default function InitiativesText({ id, heading, body }) {
alphabetize these props please

2021-02-03 22:39 UTC, asasmith approved these changes

2021-02-03 22:39 UTC, merged